### ISSUE TITLE
Exception on no last log?

### ISSUE THREAD

**Issue by arnaudruffin** [Orange-OpenSource/autosleep#130]
```
2016-01-25T15:41:57.41+0100 [App/0]      OUT DEBUG o.c.a.w.remote.CloudFoundryApi(37) - Getting application info for app static_test
2016-01-25T15:41:57.43+0100 [App/0]      OUT DEBUG o.c.a.u.s.s.AutosleepServiceInstanceService(123) - getServiceInstance - 9aef4538-b7cf-4064-ac54-28f8d0063509
2016-01-25T15:41:57.47+0100 [App/0]      OUT DEBUG o.c.a.u.s.s.ApplicationBindingService(81) - deleteServiceInstanceBinding - 362b04c2-8bf7-4289-9976-59d51408caa4
2016-01-25T15:41:58.07+0100 [App/0]      OUT DEBUG o.c.a.w.remote.CloudFoundryApi(40) - Building ApplicationInfo(state)
2016-01-25T15:41:58.07+0100 [App/0]      OUT DEBUG o.c.a.w.ApplicationStopper(84) - Checking on app 3a4e9275-e937-4735-b272-84ddea21b1f6 state
2016-01-25T15:41:58.08+0100 [App/0]      OUT ERROR o.c.a.w.ApplicationStopper(99) - unsuspected error
2016-01-25T15:41:58.08+0100 [App/0]      OUT java.lang.NullPointerException: null
2016-01-25T15:41:58.08+0100 [App/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.checkActiveApplication(ApplicationStopper.java:118) [classes/:na]
2016-01-25T15:41:58.08+0100 [App/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.handleApplicationEnrolled(ApplicationStopper.java:92) [classes/:na]
2016-01-25T15:41:58.08+0100 [App/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.lambda$run$8(ApplicationStopper.java:58) [classes/:na]
2016-01-25T15:41:58.08+0100 [App/0]      OUT    at org.cloudfoundry.autosleep.util.ApplicationLocker.executeThreadSafe(ApplicationLocker.java:28) ~[classes/:na]
2016-01-25T15:41:58.08+0100 [App/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.run(ApplicationStopper.java:52) [classes/:na]
2016-01-25T15:41:58.08+0100 [App/0]      OUT    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_65-]
2016-01-25T15:41:58.08+0100 [App/0]      OUT    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_65-]
2016-01-25T15:41:58.08+0100 [App/0]      OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_65-]
2016-01-25T15:41:58.08+0100 [App/0]      OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_65-]
2016-01-25T15:41:58.08+0100 [App/0]      OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_65-]
2016-01-25T15:41:58.08+0100 [App/0]      OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_65-]
2016-01-25T15:41:58.08+0100 [App/0]      OUT    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65-]
2016-01-25T15:41:58.08+0100 [App/0]      OUT DEBUG o.c.a.w.s.AbstractPeriodicTask(30) - Rescheduling in PT20S
2016-01-25T15:41:58.08+0100 [App/0]      OUT DEBUG o.c.a.worker.scheduling.Clock(35) - scheduleTask - task 9aef4538-b7cf-4064-ac54-28f8d0063509-3a4e9275-e937-4735-b272-84ddea21b1f6
2016-01-25T15:41:58.12+0100 [App/0]      OUT DEBUG o.c.a.u.s.s.ApplicationBindingService(90) - deleteServiceInstanceBinding on app 
2016-01-25T15:41:58.18+0100 [RTR/0]      OUT autosleep.cf.ns.nd-paas.itn.ftgroup - [25/01/2016:14:41:57 +0000] "DELETE /v2/service_instances/9aef4538-b7cf-4064-ac54-28f8d0063509/service_bindings/362b04c2-8bf7-4289-9976-59d51408caa4?plan_id=78C0A1DB-ACC9-4B6D-AF22-A1EF63C2CE06&service_id=autosleep-dev HTTP/1.1" 200 0 2 "-" "HTTPClient/1.0 (2.6.0.1, ruby 2.2.3 (2015-08-18))" 192.
```

**Comment by arnaudruffin** [comment]
May be the same issue:

```
2016-01-25T16:07:22.94+0100 [App/0]      OUT DEBUG o.c.a.w.ApplicationStopper(84) - Checking on app a898b767-1ff3-4a06-9088-d16657546d2c state
2016-01-25T16:07:22.94+0100 [App/0]      OUT ERROR o.c.a.w.ApplicationStopper(99) - unsuspected error
2016-01-25T16:07:22.94+0100 [App/0]      OUT java.lang.NullPointerException: null
2016-01-25T16:07:22.94+0100 [App/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.checkActiveApplication(ApplicationStopper.java:118) [classes/:na]
2016-01-25T16:07:22.94+0100 [App/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.handleApplicationEnrolled(ApplicationStopper.java:92) [classes/:na]
```
