### ISSUE TITLE
Dao exception on service deletion

### ISSUE THREAD

**Issue by arnaudruffin** [Orange-OpenSource/autosleep#131]
```
2016-01-25T15:44:10.82+0100 [App/0]      OUT DEBUG o.c.a.u.s.s.AutosleepServiceInstanceService(78) - createServiceInstance - 39a74b12-9e2e-4ec3-b686-3ab94d133a55
2016-01-25T15:44:10.83+0100 [App/0]      OUT DEBUG o.c.a.u.s.s.p.ParameterReaderFactory(101) - forcedAutoEnrollment forced
2016-01-25T15:44:10.83+0100 [App/0]      OUT DEBUG o.c.a.u.s.s.p.ParameterReaderFactory(34) - pattern PT6S
2016-01-25T15:44:10.84+0100 [App/0]      OUT DEBUG o.c.a.u.s.s.p.ParameterReaderFactory(68) - excludeFromAutoEnrollment .*
2016-01-25T15:44:10.85+0100 [RTR/0]      OUT autosleep.cf.ns.nd-paas.itn.ftgroup - [25/01/2016:14:44:10 +0000] "PUT /v2/service_instances/39a74b12-9e2e-4ec3-b686-3ab94d133a55 HTTP/1.1" 422 291 120 "-" "HTTPClient/1.0 (2.6.0.1, ruby 2.2.3 (2015-08-18))" 192.168.26.30:39747 x_forwarded_for:"192.168.26.52" x_forwarded_proto:"http" vcap_request_id:b096ca0b-82ce-4eb5-635b-1f7e4449b9ab response_time:0.025308252 app_id:3048d795-f031-435f-85e8-71dce339e869
2016-01-25T15:44:11.40+0100 [App/0]      OUT DEBUG o.c.a.u.s.s.AutosleepServiceInstanceService(180) - deleteServiceInstance - 39a74b12-9e2e-4ec3-b686-3ab94d133a55
2016-01-25T15:44:11.41+0100 [App/0]      OUT WARN  o.c.c.s.c.BaseController(62) - Exception
2016-01-25T15:44:11.41+0100 [App/0]      OUT org.springframework.dao.EmptyResultDataAccessException: No class org.cloudfoundry.autosleep.dao.model.SpaceEnrollerConfig entity with id 39a74b12-9e2e-4ec3-b686-3ab94d133a55 exists!
2016-01-25T15:44:11.41+0100 [App/0]      OUT    at org.springframework.data.jpa.repository.support.SimpleJpaRepository.delete(SimpleJpaRepository.java:147) ~[spring-data-jpa-1.9.0.RELEASE.jar!/:na]
2016-01-25T15:44:11.41+0100 [App/0]      OUT    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65-]
2016-01-25T15:44:11.41+0100 [App/0]      OUT    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65-]
2016-01-25T15:44:11.41+0100 [App/0]      OUT    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65-]
2016-01-25T15:44:11.41+0100 [App/0]      OUT    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65-]
2016-01-25T15:44:11.41+0100 [App/0]      OUT    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:475) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
2016-01-25T15:44:11.41+0100 [App/0]      OUT    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:460) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
2016-01-25T15:44:11.41+0100 [App/0]      OUT    at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:432) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
2016-01-25T15:44:11.41+0100 [App/0]      OUT    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
```

**Comment by antechrestos** [comment]
Maybe because you dropped all database content without cleaning data in Cloudfoundry?

**Comment by arnaudruffin** [comment]
No, as you can see the service instance is created on the first line without any problem
