### ISSUE TITLE
OAuth2AccessDeniedException

### ISSUE THREAD

**Issue by arnaudruffin** [Orange-OpenSource/autosleep#137]
```
2016-02-12T09:12:35.45+0100 [App/0]      OUT DEBUG o.c.a.w.remote.CloudFoundryApi(104) - Getting applicationActivity 46afcf69-3ecd-47ec-abca-76355c30477b
2016-02-12T09:12:35.51+0100 [App/0]      OUT DEBUG o.c.a.u.s.s.AutosleepServiceInstanceService(123) - getServiceInstance - 9eed9aa9-3f25-4980-ab50-5448fa61cc64
2016-02-12T09:12:35.60+0100 [App/0]      OUT DEBUG o.c.a.u.s.s.ApplicationBindingService(81) - deleteServiceInstanceBinding - bc07a64b-eb1c-448c-998c-818a19e58404
2016-02-12T09:12:36.37+0100 [App/0]      OUT ERROR o.c.a.w.ApplicationStopper(104) - unsuspected error
2016-02-12T09:12:36.37+0100 [App/0]      OUT org.springframework.security.oauth2.client.resource.OAuth2AccessDeniedException: Error requesting access token.
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport.retrieveToken(OAuth2AccessTokenSupport.java:145) ~[spring-security-oauth2-2.0.8.RELEASE.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.security.oauth2.client.token.grant.password.ResourceOwnerPasswordAccessTokenProvider.obtainAccessToken(ResourceOwnerPasswordAccessTokenProvider.java:47) ~[spring-security-oauth2-2.0.8.RELEASE.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainNewAccessTokenInternal(AccessTokenProviderChain.java:142) ~[spring-security-oauth2-2.0.8.RELEASE.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainAccessToken(AccessTokenProviderChain.java:118) ~[spring-security-oauth2-2.0.8.RELEASE.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:221) ~[spring-security-oauth2-2.0.8.RELEASE.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173) ~[spring-security-oauth2-2.0.8.RELEASE.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.security.oauth2.client.OAuth2RestTemplate.createRequest(OAuth2RestTemplate.java:105) ~[spring-security-oauth2-2.0.8.RELEASE.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:592) ~[spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128) ~[spring-security-oauth2-2.0.8.RELEASE.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:280) ~[spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.cloudfoundry.client.spring.util.AbstractSpringOperations$3.apply(AbstractSpringOperations.java:110) ~[cloudfoundry-client-spring-4f3c645.jar!/:2.0.0.BUILD-SNAPSHOT]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.cloudfoundry.client.spring.util.AbstractSpringOperations$3.apply(AbstractSpringOperations.java:102) ~[cloudfoundry-client-spring-4f3c645.jar!/:2.0.0.BUILD-SNAPSHOT]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.cloudfoundry.client.spring.util.AbstractSpringOperations$2$1.accept(AbstractSpringOperations.java:84) ~[cloudfoundry-client-spring-4f3c645.jar!/:2.0.0.BUILD-SNAPSHOT]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.cloudfoundry.client.spring.util.AbstractSpringOperations$2$1.accept(AbstractSpringOperations.java:78) ~[cloudfoundry-client-spring-4f3c645.jar!/:2.0.0.BUILD-SNAPSHOT]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at reactor.core.publisher.FluxYieldingEmitter$YieldingSignalEmitter.request(FluxYieldingEmitter.java:76) ~[reactor-core-2.5.0.BUILD-20160210.191749-340.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at reactor.core.util.DeferredSubscription.set(DeferredSubscription.java:71) ~[reactor-core-2.5.0.BUILD-20160210.191749-340.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at reactor.core.publisher.FluxPublishOn$PublishOnPipeline.onSubscribe(FluxPublishOn.java:131) ~[reactor-core-2.5.0.BUILD-20160210.191749-340.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at reactor.core.subscriber.SignalEmitter.start(SignalEmitter.java:170) ~[reactor-core-2.5.0.BUILD-20160210.191749-340.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at reactor.core.publisher.FluxYieldingEmitter.subscribe(FluxYieldingEmitter.java:43) ~[reactor-core-2.5.0.BUILD-20160210.191749-340.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at reactor.rx.StreamSource.subscribe(StreamSource.java:71) ~[reactor-stream-2.5.0.BUILD-20160210.193010-335.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at reactor.core.util.ScalarSubscription.trySubscribeScalarMap(ScalarSubscription.java:93) ~[reactor-core-2.5.0.BUILD-20160210.191749-340.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:93) ~[reactor-core-2.5.0.BUILD-20160210.191749-340.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at reactor.rx.StreamSource.subscribe(StreamSource.java:71) ~[reactor-stream-2.5.0.BUILD-20160210.193010-335.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at reactor.core.publisher.FluxPublishOn$SourceSubscribeTask.run(FluxPublishOn.java:318) ~[reactor-core-2.5.0.BUILD-20160210.191749-340.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1072) ~[reactor-core-2.5.0.BUILD-20160210.191749-340.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1054) ~[reactor-core-2.5.0.BUILD-20160210.191749-340.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at reactor.core.publisher.WorkQueueProcessor$QueueSubscriberLoop.run(WorkQueueProcessor.java:849) ~[reactor-core-2.5.0.BUILD-20160210.191749-340.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_65-]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_65-]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65-]
2016-02-12T09:12:36.37+0100 [App/0]      OUT Caused by: org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport$AccessTokenErrorHandler.handleError(OAuth2AccessTokenSupport.java:244) ~[spring-security-oauth2-2.0.8.RELEASE.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:565) ~[spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport.retrieveToken(OAuth2AccessTokenSupport.java:137) ~[spring-security-oauth2-2.0.8.RELEASE.jar!/:na]
2016-02-12T09:12:36.37+0100 [App/0]      OUT    ... 30 common frames omitted
2016-02-12T09:12:36.38+0100 [App/0]      OUT DEBUG o.c.a.w.s.AbstractPeriodicTask(30) - Rescheduling in PT20S
2016-02-12T09:12:36.38+0100 [App/0]      OUT DEBUG o.c.a.worker.scheduling.Clock(35) - scheduleTask - task 9eed9aa9-3f25-4980-ab50-5448fa61cc64-46afcf69-3ecd-47ec-abca-76355c30477b
2016-02-12T09:12:36.67+0100 [App/0]      OUT DEBUG o.c.a.u.s.s.ApplicationBindingService(90) - deleteServiceInstanceBinding on app 
```

**Comment by arnaudruffin** [comment]
New cf-java-client isn't shipped with default clientId/clientSecret...
