### ISSUE TITLE
Auto Sleep failing: NPE in getApplicationActivity()

### ISSUE THREAD

**Issue by ghost** [Orange-OpenSource/autosleep#143]
Hi 
Getting NPE while initializing the watche. Here is the log - 

2016-02-18T08:09:26.59+0000 [HEALTH/0]   OUT Exit status 0
2016-02-18T08:09:48.19+0000 [APP/0]      OUT DEBUG o.c.a.s.s.AutoSleepServiceInstanceService(46) - getServiceInstance - a48514b6-4ea4-45ba-9bee-5cfa6b62b61f
2016-02-18T08:09:48.19+0000 [APP/0]      OUT DEBUG o.c.a.s.s.AutoSleepServiceInstanceBindingService(37) - createServiceInstanceBinding - 05436dfd-ffcc-4d94-9f1a-1a0b3a51268a
2016-02-18T08:09:48.20+0000 [APP/0]      OUT DEBUG o.c.a.scheduling.GlobalWatcher(80) - Initializing a watch on app eae6618b-4cea-464c-87c9-eda608278e19, for an interval of PT24H
2016-02-18T08:09:48.21+0000 [APP/0]      OUT DEBUG o.c.autosleep.scheduling.Clock(48) - schedule - task 05436dfd-ffcc-4d94-9f1a-1a0b3a51268a
2016-02-18T08:09:48.22+0000 [RTR/0]      OUT autosleep.local.micropcf.io - [18/02/2016:08:09:48 +0000] "PUT /v2/service_instances/a48514b6-4ea4-45ba-9bee-5cfa6b62b61f/service_bindings/05436dfd-ffcc-4d94-9f1a-1a0b3a51268a HTTP/1.1" 201 193 18 "-" "HTTPClient/1.0 (2.6.0.1, ruby 2.2.3 (2015-08-18))" 19
2.168.11.11:21551 x_forwarded_for:"192.168.11.11" x_forwarded_proto:"-" vcap_request_id:8b15edbf-0fdb-47ee-6276-0755f2e43f35 response_time:0.051294112 app_id:69e54164-47f1-4fdf-924e-e420ddc9b94d
2016-02-18T08:09:48.22+0000 [APP/0]      OUT DEBUG o.c.a.s.AppStateChecker(31) - Checking on app eae6618b-4cea-464c-87c9-eda608278e19 state, for taskId 05436dfd-ffcc-4d94-9f1a-1a0b3a51268a
2016-02-18T08:09:48.22+0000 [APP/0]      OUT ERROR o.c.a.remote.CloudFoundryApi(73) - error
2016-02-18T08:09:48.22+0000 [APP/0]      OUT java.lang.NullPointerException: null
2016-02-18T08:09:48.22+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.remote.CloudFoundryApi.getApplicationInfo(CloudFoundryApi.java:47) ~[classes/:na]
2016-02-18T08:09:48.22+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.scheduling.AppStateChecker.run(AppStateChecker.java:32) [classes/:na]
2016-02-18T08:09:48.22+0000 [APP/0]      OUT    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_65-]
2016-02-18T08:09:48.22+0000 [APP/0]      OUT    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65-]
2016-02-18T08:09:48.22+0000 [APP/0]      OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_65-]
2016-02-18T08:09:48.22+0000 [APP/0]      OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_65-]
2016-02-18T08:09:48.22+0000 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65-]
2016-02-18T08:09:48.22+0000 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65-]
2016-02-18T08:09:48.22+0000 [APP/0]      OUT    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65-]

Please note I have deployed the v0.1.0 using WAR file.

**Comment by antechrestos** [comment]
@tanmoypal: Looking at the source of the v0.1.0 tag, I see that client is null. Didn't you have any stack before? 
Did you provide the properties:
- cf.client.target.endpoint
- cf.client.skip.ssl.validation (optional: default `false`)
- cf.client.username
- cf.client.password
- cf.client.clientId
- cf.client.clientSecret

If so, at start time the client is built and attempts to  login with the given informations. If any trouble occurs in this phase, the client remains not built, leading to the NPE you mentionned above.

**Comment by ghost** [comment]
@antechrestos : I added the following properties as JAVA_OPTS- 

 -Dcf.client.target.endpoint=https://api.local.micropcf.io
 -Dcf.client.skip.ssl.validation=true
 -Dcf.client.username=admin
 -Dcf.client.password=admin
 -Dsecurity.user.name=admin
 -Dsecurity.user.password=admin

But as the clientId and clientSecret are mentioned as optional field, I did not add them. Is it mandatory to add them?

**Comment by antechrestos** [comment]
@tanmoypal In this version it was. In the next we will provide You can use:
`cf.client.clientId=cf`

and

`cf.client.clientSecret=` (empty)

**Comment by ghost** [comment]
@antechrestos :  I have tried using this but did not work. Facing two issues here - 

A) Not able to connect to CF - 

2016-02-18T13:00:00.26+0000 [APP/0]      OUT 2016-02-18 13:00:00.260 ERROR 23 --- [ost-startStop-1] o.c.a.w.r.c.CloudfoundryClientBuilder    : CloudFoundryApi - failure while login
2016-02-18T13:00:00.26+0000 [APP/0]      OUT java.lang.RuntimeException: java.net.UnknownHostException: https://api.local.micropcf.io
2016-02-18T13:00:00.26+0000 [APP/0]      OUT    at org.cloudfoundry.client.spring.SpringCloudFoundryClient.trustHost(SpringCloudFoundryClient.java:435)
2016-02-18T13:00:00.26+0000 [APP/0]      OUT    at org.cloudfoundry.client.spring.SpringCloudFoundryClient.<init>(SpringCloudFoundryClient.java:160)
2016-02-18T13:00:00.26+0000 [APP/0]      OUT    at org.cloudfoundry.client.spring.SpringCloudFoundryClient.<init>(SpringCloudFoundryClient.java:144)
2016-02-18T13:00:00.26+0000 [APP/0]      OUT    at org.cloudfoundry.client.spring.SpringCloudFoundryClient$SpringCloudFoundryClientBuilder.build(SpringCloudFoundryClient.java:545)
2016-02-18T13:00:00.26+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.remote.config.CloudfoundryClientBuilder.initClients(CloudfoundryClientBuilder.java:52)
2016-02-18T13:00:00.26+0000 [APP/0]      OUT    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

B) Not able to connect to the mysql service - 

2016-02-18T12:59:48.64+0000 [APP/0]      OUT 2016-02-18 12:59:48.642  WARN 23 --- [           main] o.s.cloud.AbstractCloudConnector         : No suitable service info creator found for service mysql Did you forget to add a ServiceInfoCreator?
2016-02-18T12:59:48.64+0000 [APP/0]      OUT 2016-02-18 12:59:48.648  WARN 23 --- [           main] o.s.cloud.AbstractCloudConnector         : No suitable service info creator found for service mysql Did you forget to add a ServiceInfoCreator?
2016-02-18T12:59:48.65+0000 [APP/0]      OUT 2016-02-18 12:59:48.649  WARN 23 --- [           main] o.s.cloud.config.CloudScanHelper         : Unable to create service for mysql during service scanning. Skiping.

Please note, I am using a  MicroPCF based local CF set up with an User Provided mysql service here.

**Comment by antechrestos** [comment]
### The CF endpoint

In the v0.1.0.0 we used the v1.X [cf-java-client](https://github.com/cloudfoundry/cf-java-client/). The host need the scheme in the properties
Are you sure it is available?

### The repository

Looking at the source I see that we did not support the mysql service.However we used to support RAM (if you restart you lose everything) and Redis  as a persistance service.

See the example below:

``` yml
applications:
- name: my-autosleep
  memory: 1G
  instances: 1
  host: my-autosleep
  domain: cf.ns.nd-paas.itn.ftgroup
  path: build/libs/org.cloudfoundry.autosleep-0.1.0-SNAPSHOT.war
  services:
    - logs
    - redis
  buildpack: java_buildpack
  env:
    JAVA_OPTS: >
      -Dcf.client.target.endpoint= https://api.local.micropcf.io
      -Dcf.client.skip.ssl.validation=true
      -Dcf.client.username=<username>
      -Dcf.client.password=<password>
      -Dcf.client.clientId=cf
      -Dcf.client.clientSecret=
```

**Comment by ghost** [comment]
Now I am using autosleep v0.2.0 tags on MicroPCF v0.6.0. I am able to deploy the app successfully and I am able to create the servicebroker as well. But while creating service instances I am getting NPE -

2016-02-22T05:32:42.27+0000 [APP/0]      OUT WARN  o.c.c.s.c.BaseController(62) - Exception
2016-02-22T05:32:42.27+0000 [APP/0]      OUT java.lang.NullPointerException: null
2016-02-22T05:32:42.27+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.ui.servicebroker.service.AutosleepServiceInstanceService.consumeParameter(AutosleepServiceInstanceService.java:215) ~[classes/:na]
2016-02-22T05:32:42.27+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.ui.servicebroker.service.AutosleepServiceInstanceService.createServiceInstance(AutosleepServiceInstanceService.java:83) ~[classes/:na]
2016-02-22T05:32:42.27+0000 [APP/0]      OUT    at org.cloudfoundry.community.servicebroker.controller.ServiceInstanceController.createServiceInstance(ServiceInstanceController.java:49) ~[spring-boot-cf-service-broker-facbe53.jar!/:na]
2016-02-22T05:32:42.27+0000 [APP/0]      OUT    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65-]
2016-02-22T05:32:42.27+0000 [APP/0]      OUT    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65-]
2016-02-22T05:32:42.27+0000 [APP/0]      OUT    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65-]
2016-02-22T05:32:42.27+0000 [APP/0]      OUT    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65-]
2016-02-22T05:32:42.27+0000 [APP/0]      OUT    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222) ~[spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-02-22T05:32:42.27+0000 [APP/0]      OUT    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) ~[spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-02-22T05:32:42.27+0000 [APP/0]      OUT    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
2016-02-22T05:32:42.27+0000 [APP/0]      OUT    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
2016-02-22T05:32:42.27+0000 [APP/0]      OUT    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705) 

While debugging I saw that the request.getParameters() is throwing null.

2016-02-22T09:22:17.20+0000 [APP/0]      OUT 2016-02-22 09:22:17.201  WARN 12 --- [nio-8080-exec-2] .a.u.s.s.AutosleepServiceInstanceService : createServiceInstance - 52a2add6-9843-4529-84d1-615c4476d831
2016-02-22T09:22:17.20+0000 [APP/0]      OUT 2016-02-22 09:22:17.202  WARN 12 --- [nio-8080-exec-2] .a.u.s.s.AutosleepServiceInstanceService : Request paramter details : => null
2016-02-22T09:22:17.23+0000 [APP/0]      OUT 2016-02-22 09:22:17.238  WARN 12 --- [nio-8080-exec-2] .a.u.s.s.AutosleepServiceInstanceService : Calling consumeParameter with : request = org.cloudfoundry.community.servicebroker.model.CreateServiceInstanceRequest@9984df57
2016-02-22T09:22:17.23+0000 [APP/0]      OUT 2016-02-22 09:22:17.238  WARN 12 --- [nio-8080-exec-2] .a.u.s.s.AutosleepServiceInstanceService : Inside consumeParameter : reader =org.cloudfoundry.autosleep.ui.servicebroker.service.parameters.ParameterReaderFactory$3@116c9107 parameters : null
2016-02-22T09:22:17.25+0000 [APP/0]      OUT 2016-02-22 09:22:17.251  WARN 12 --- [nio-8080-exec-2] o.c.c.s.controller.BaseController        : Exception
2016-02-22T09:22:17.25+0000 [APP/0]      OUT java.lang.NullPointerException: null
2016-02-22T09:22:17.25+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.ui.servicebroker.service.AutosleepServiceInstanceService.consumeParameter(AutosleepServiceInstanceService.java:217)
2016-02-22T09:22:17.25+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.ui.servicebroker.service.AutosleepServiceInstanceService.createServiceInstance(AutosleepServiceInstanceService.java:84)
2016-02-22T09:22:17.25+0000 [APP/0]      OUT    at org.cloudfoundry.community.servicebroker.controller.ServiceInstanceController.createServiceInstance(ServiceInstanceController.java:49)
2016-02-22T09:22:17.25+0000 [APP/0]      OUT    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by antechrestos** [comment]
@tanmoypal I made a new release that fixes this issue. Thank you for your support.

**Comment by ghost** [comment]
Thanks @antechrestos. Now it's started working.

**Comment by antechrestos** [comment]
@tanmoypal Good to know . Thank you for your patience :smile:
