### ISSUE TITLE
Route binding error

### ISSUE THREAD

**Issue by arnaudruffin** [Orange-OpenSource/autosleep#162]
Apparently, the retrieved routeid is not an id

```


2016-04-18T11:37:11.99+0200 [APP/0]      OUT DEBUG o.c.a.w.remote.CloudFoundryApi(198) - getApplicationActivity -  0a9393b0-7db8-48df-8699-77543e84651a
2016-04-18T11:37:12.15+0200 [APP/0]      OUT DEBUG o.c.a.w.ApplicationStopper(115) - Checking on app 0a9393b0-7db8-48df-8699-77543e84651a state
2016-04-18T11:37:12.15+0200 [APP/0]      OUT DEBUG o.c.a.util.LastDateComputer(43) - computeLastDate - lastEvent.isAfter(lastLog) = false
2016-04-18T11:37:12.15+0200 [APP/0]      OUT DEBUG o.c.a.w.ApplicationStopper(85) - last event:  2016-04-18T09:36:11.985Z
2016-04-18T11:37:12.15+0200 [APP/0]      OUT INFO  o.c.a.w.ApplicationStopper(151) - Stopping app [sample / 0a9393b0-7db8-48df-8699-77543e84651a], last event: org.cloudfoundry.autosleep.dao.model.ApplicationInfo$DiagnosticInfo$ApplicationEvent@768d9, last log: org.cloudfoundry.autosleep.dao.model.ApplicationInfo$DiagnosticInfo$ApplicationLog@e2e4a52b
2016-04-18T11:37:12.15+0200 [APP/0]      OUT DEBUG o.c.a.w.remote.CloudFoundryApi(269) - listApplicationRoutes
2016-04-18T11:37:12.22+0200 [APP/0]      OUT DEBUG o.c.a.w.remote.CloudFoundryApi(117) - bind - 1
2016-04-18T11:37:12.31+0200 [APP/0]      OUT INFO  o.s.b.a.a.l.AuditListener(42) - AuditEvent [timestamp=Mon Apr 18 09:37:12 UTC 2016, principal=oto, type=AUTHENTICATION_SUCCESS, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@7798: RemoteIpAddress: 192.168.26.6; SessionId: null}]
2016-04-18T11:37:12.31+0200 [APP/0]      OUT DEBUG o.c.a.u.s.s.AutosleepBindingService(84) - createServiceInstanceBinding - bb17b024-fd53-4466-bff7-405b4b94b2d8
2016-04-18T11:37:12.32+0200 [APP/0]      OUT DEBUG o.c.a.u.s.s.AutosleepBindingService(120) - creating binding bb17b024-fd53-4466-bff7-405b4b94b2d8 for route sample.cf.ns.nd-paas.itn.ftgroup
2016-04-18T11:37:12.32+0200 [APP/0]      OUT DEBUG o.c.a.w.remote.CloudFoundryApi(317) - listRouteApplications
2016-04-18T11:37:12.43+0200 [RTR/0]      OUT autosleep-arno.cf.ns.nd-paas.itn.ftgroup - [18/04/2016:09:37:12 +0000] "PUT /v2/service_instances/2d93da5d-f229-4979-b515-901d6c7f07f8/service_bindings/bb17b024-fd53-4466-bff7-405b4b94b2d8 HTTP/1.1" 500 119 63 "-" "HTTPClient/1.0 (2.6.0.1, ruby 2.2.4 (2015-12-16))" 192.168.26.30:49292 x_forwarded_for:"192.168.26.52" x_forwarded_proto:"http" vcap_request_id:9215d186-feb8-4b87-4da2-4e4aabcdfff5 response_time:0.121520422 app_id:d9856915-86da-44bf-94e0-28641aad1bec
2016-04-18T11:37:12.43+0200 [APP/0]      OUT ERROR r.c.publisher.SchedulerGroup(477) - Unrouted exception
2016-04-18T11:37:12.43+0200 [APP/0]      OUT org.cloudfoundry.client.v2.CloudFoundryException: CF-RouteNotFound(210002): The route could not be found: sample.cf.ns.nd-paas.itn.ftgroup
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at org.cloudfoundry.spring.client.v2.CloudFoundryExceptionBuilder.build(CloudFoundryExceptionBuilder.java:47) ~[cloudfoundry-client-spring-2.0.0.M1.jar!/:2.0.0.M1]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$null$1(AbstractSpringOperations.java:72) ~[cloudfoundry-client-spring-2.0.0.M1.jar!/:2.0.0.M1]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at reactor.core.publisher.FluxYieldingEmitter$YieldingSignalEmitter.request(FluxYieldingEmitter.java:72) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at reactor.core.util.DeferredSubscription.request(DeferredSubscription.java:92) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at reactor.core.publisher.FluxPublishOn$PublishOnPipeline.run(FluxPublishOn.java:164) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1081) [reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1063) [reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at reactor.core.publisher.WorkQueueProcessor$QueueSubscriberLoop.run(WorkQueueProcessor.java:842) [reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65-]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65-]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65-]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT Caused by: org.springframework.web.client.HttpClientErrorException: 404 Not Found
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:165) ~[spring-security-oauth2-2.0.9.RELEASE.jar!/:na]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128) ~[spring-security-oauth2-2.0.9.RELEASE.jar!/:na]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:280) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$get$3(AbstractSpringOperations.java:85) ~[cloudfoundry-client-spring-2.0.0.M1.jar!/:2.0.0.M1]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$null$1(AbstractSpringOperations.java:66) ~[cloudfoundry-client-spring-2.0.0.M1.jar!/:2.0.0.M1]
2016-04-18T11:37:12.43+0200 [APP/0]      OUT    ... 9 common frames omitted
2016-04-18T11:37:12.49+0200 [APP/0]      OUT ERROR o.c.a.w.ApplicationStopper(128) - error while requesting remote api
2016-04-18T11:37:12.49+0200 [APP/0]      OUT org.cloudfoundry.autosleep.worker.remote.CloudFoundryException: org.cloudfoundry.client.v2.CloudFoundryException: CF-ServiceBrokerBadResponse(10001): Service broker error: Can't check applications map to this route id
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.remote.CloudFoundryApi.waitForResult(CloudFoundryApi.java:361) ~[classes/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.remote.CloudFoundryApi.bind(CloudFoundryApi.java:124) ~[classes/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.remote.CloudFoundryApi.bindRoutes(CloudFoundryApi.java:141) ~[classes/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.putApplicationToSleep(ApplicationStopper.java:158) [classes/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.checkActiveApplication(ApplicationStopper.java:88) [classes/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.handleApplicationEnrolled(ApplicationStopper.java:125) [classes/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.lambda$run$19(ApplicationStopper.java:179) [classes/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.util.ApplicationLocker.executeThreadSafe(ApplicationLocker.java:47) ~[classes/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.run(ApplicationStopper.java:172) [classes/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_65-]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_65-]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_65-]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_65-]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_65-]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_65-]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65-]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT Caused by: org.cloudfoundry.client.v2.CloudFoundryException: CF-ServiceBrokerBadResponse(10001): Service broker error: Can't check applications map to this route id
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at org.cloudfoundry.spring.client.v2.CloudFoundryExceptionBuilder.build(CloudFoundryExceptionBuilder.java:47) ~[cloudfoundry-client-spring-2.0.0.M1.jar!/:2.0.0.M1]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$null$1(AbstractSpringOperations.java:72) ~[cloudfoundry-client-spring-2.0.0.M1.jar!/:2.0.0.M1]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at reactor.core.publisher.FluxYieldingEmitter$YieldingSignalEmitter.request(FluxYieldingEmitter.java:72) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at reactor.core.util.DeferredSubscription.set(DeferredSubscription.java:71) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at reactor.core.publisher.FluxPublishOn$PublishOnPipeline.onSubscribe(FluxPublishOn.java:126) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at reactor.core.subscriber.SignalEmitter.start(SignalEmitter.java:170) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at reactor.core.publisher.FluxYieldingEmitter.subscribe(FluxYieldingEmitter.java:43) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:152) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:169) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at reactor.core.publisher.FluxPublishOn$SourceSubscribeTask.run(FluxPublishOn.java:308) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1081) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1063) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at reactor.core.publisher.WorkQueueProcessor$QueueSubscriberLoop.run(WorkQueueProcessor.java:842) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    ... 3 common frames omitted
2016-04-18T11:37:12.49+0200 [APP/0]      OUT Caused by: org.springframework.web.client.HttpServerErrorException: 502 Bad Gateway
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-18T11:37:12.49+0200 [APP/0]      OUT    at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler
```

**Comment by arnaudruffin** [comment]
Duplicate of #164
