### ISSUE TITLE
Route binding : CF-ServiceBrokerBadResponse(10001) due to 502 Bad Gateway

### ISSUE THREAD

**Issue by arnaudruffin** [Orange-OpenSource/autosleep#165]
While testing the binding of a route, we get a CF-ServiceBrokerBadResponse(10001) whenever trying to send a response.

```
2016-04-18T15:49:39.35+0200 [APP/0]      OUT Caused by: org.cloudfoundry.client.v2.CloudFoundryException: CF-ServiceBrokerBadResponse(10001): The service broker returned an invalid response for the request to http://autosleep-arno.cf.ns.nd-paas.itn.ftgroup/v2/service_instances/141f0d49-59f5-493f-afb6-086b427b0730/service_bindings/b29d5495-e4b5-404c-986e-834d092b4b58. Status Code: 201 Created, Body: {"route_service_url":"autosleep-arno.cf.ns.nd-paas.itn.ftgroup/proxy/b29d5495-e4b5-404c-986e-834d092b4b58"}
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at org.cloudfoundry.spring.client.v2.CloudFoundryExceptionBuilder.build(CloudFoundryExceptionBuilder.java:47) ~[cloudfoundry-client-spring-2.0.0.M1.jar!/:2.0.0.M1]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$null$1(AbstractSpringOperations.java:72) ~[cloudfoundry-client-spring-2.0.0.M1.jar!/:2.0.0.M1]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at reactor.core.publisher.FluxYieldingEmitter$YieldingSignalEmitter.request(FluxYieldingEmitter.java:72) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at reactor.core.util.DeferredSubscription.request(DeferredSubscription.java:92) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at reactor.core.publisher.FluxPublishOn$PublishOnPipeline.run(FluxPublishOn.java:164) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1081) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1063) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at reactor.core.publisher.WorkQueueProcessor$QueueSubscriberLoop.run(WorkQueueProcessor.java:842) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    ... 3 common frames omitted
2016-04-18T15:49:39.35+0200 [APP/0]      OUT Caused by: org.springframework.web.client.HttpServerErrorException: 502 Bad Gateway
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:85) ~[spring-security-oauth2-2.0.9.RELEASE.jar!/:na]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128) ~[spring-security-oauth2-2.0.9.RELEASE.jar!/:na]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:534) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$putWithBody$10(AbstractSpringOperations.java:139) ~[cloudfoundry-client-spring-2.0.0.M1.jar!/:2.0.0.M1]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$null$1(AbstractSpringOperations.java:66) ~[cloudfoundry-client-spring-2.0.0.M1.jar!/:2.0.0.M1]
2016-04-18T15:49:39.35+0200 [APP/0]      OUT    ... 9 common frames omitted

```

**Comment by arnaudruffin** [comment]
Compatibility check:
Our service broker is based on [ spring-cloud-cloudfoundry-service-broker](https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker), (see PR #163).

The library require Service Broker API: 2.8 (see project REAME.md),
which is supported since:
- Final build 226 of cf-release
- v2.44.0 of the Cloud Controller API
- CLI v6.14.0

Dependencies seems not to be the issue here

**Comment by arnaudruffin** [comment]
More complete log:

```
2016-04-18T15:54:42.40+0200 [APP/0]      OUT ERROR o.c.a.w.ApplicationStopper(128) - error while requesting remote api
2016-04-18T15:54:42.40+0200 [APP/0]      OUT org.cloudfoundry.autosleep.worker.remote.CloudFoundryException: org.cloudfoundry.client.v2.CloudFoundryException: CF-ServiceBrokerBadResponse(10001): The service broker returned an invalid response for the request to http://autosleep-arno.cf.ns.nd-paas.itn.ftgroup/v2/service_instances/141f0d49-59f5-493f-afb6-086b427b0730/service_bindings/3b23dd53-7af8-4918-9f27-78f3231f53f6. Status Code: 201 Created, Body: {"route_service_url":"autosleep-arno.cf.ns.nd-paas.itn.ftgroup/proxy/3b23dd53-7af8-4918-9f27-78f3231f53f6"}
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.remote.CloudFoundryApi.waitForResult(CloudFoundryApi.java:361) ~[classes/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.remote.CloudFoundryApi.bind(CloudFoundryApi.java:124) ~[classes/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.remote.CloudFoundryApi.bindRoutes(CloudFoundryApi.java:141) ~[classes/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.putApplicationToSleep(ApplicationStopper.java:158) [classes/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.checkActiveApplication(ApplicationStopper.java:88) [classes/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.handleApplicationEnrolled(ApplicationStopper.java:125) [classes/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.lambda$run$19(ApplicationStopper.java:179) [classes/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.util.ApplicationLocker.executeThreadSafe(ApplicationLocker.java:47) ~[classes/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.run(ApplicationStopper.java:172) [classes/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_65-]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_65-]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_65-]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_65-]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_65-]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_65-]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65-]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT Caused by: org.cloudfoundry.client.v2.CloudFoundryException: CF-ServiceBrokerBadResponse(10001): The service broker returned an invalid response for the request to http://autosleep-arno.cf.ns.nd-paas.itn.ftgroup/v2/service_instances/141f0d49-59f5-493f-afb6-086b427b0730/service_bindings/3b23dd53-7af8-4918-9f27-78f3231f53f6. Status Code: 201 Created, Body: {"route_service_url":"autosleep-arno.cf.ns.nd-paas.itn.ftgroup/proxy/3b23dd53-7af8-4918-9f27-78f3231f53f6"}
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.cloudfoundry.spring.client.v2.CloudFoundryExceptionBuilder.build(CloudFoundryExceptionBuilder.java:47) ~[cloudfoundry-client-spring-2.0.0.M1.jar!/:2.0.0.M1]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$null$1(AbstractSpringOperations.java:72) ~[cloudfoundry-client-spring-2.0.0.M1.jar!/:2.0.0.M1]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at reactor.core.publisher.FluxYieldingEmitter$YieldingSignalEmitter.request(FluxYieldingEmitter.java:72) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at reactor.core.util.DeferredSubscription.set(DeferredSubscription.java:71) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at reactor.core.publisher.FluxPublishOn$PublishOnPipeline.onSubscribe(FluxPublishOn.java:126) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at reactor.core.subscriber.SignalEmitter.start(SignalEmitter.java:170) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at reactor.core.publisher.FluxYieldingEmitter.subscribe(FluxYieldingEmitter.java:43) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:152) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:169) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at reactor.core.publisher.FluxPublishOn$SourceSubscribeTask.run(FluxPublishOn.java:308) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1081) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1063) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at reactor.core.publisher.WorkQueueProcessor$QueueSubscriberLoop.run(WorkQueueProcessor.java:842) ~[reactor-core-2.5.0.M2.jar!/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    ... 3 common frames omitted
2016-04-18T15:54:42.40+0200 [APP/0]      OUT Caused by: org.springframework.web.client.HttpServerErrorException: 502 Bad Gateway
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:85) ~[spring-security-oauth2-2.0.9.RELEASE.jar!/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128) ~[spring-security-oauth2-2.0.9.RELEASE.jar!/:na]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:534) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$putWithBody$10(AbstractSpringOperations.java:139) ~[cloudfoundry-client-spring-2.0.0.M1.jar!/:2.0.0.M1]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$null$1(AbstractSpringOperations.java:66) ~[cloudfoundry-client-spring-2.0.0.M1.jar!/:2.0.0.M1]
2016-04-18T15:54:42.40+0200 [APP/0]      OUT    ... 14 common frames omitted
```

**Comment by arnaudruffin** [comment]
- CreateServiceInstanceRouteBindingResponse with no parameter ✅ 
- CreateServiceInstanceRouteBindingResponse with `null` in withRouteServiceUrl ✅

**Comment by arnaudruffin** [comment]
Seen in 
- http://docs.cloudfoundry.org/services/route-services.html 
  - Broker Responsibilities 
    - Binding Endpoint

> This URL must have a https scheme, otherwise the Cloud Controller will reject the binding. route_service_url is optional; not returning this field enables a broker to dynamically configure a network component already in the request path for the route, requiring no change in the Cloud Foundry router.
