### ISSUE TITLE
Getting Subscriber timed out exception

### ISSUE THREAD

**Issue by paltanmoy** [Orange-OpenSource/autosleep#186]
My autosleep instance was running perfectly, all of a sudden it stopped working throwing java.lang.IllegalStateException: Subscriber timed out exception. Do you have any idea on this ?
## Error Log 

ourceHttpRequestHandler]
2016-05-03T10:14:52.78+0000 [APP/0]      OUT 2016-05-03 10:14:52.784  INFO 14 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@33c386ef: startup date [Tue May 03 10:13:39 UTC 2016]; root of context hierarchy
2016-05-03T10:14:56.91+0000 [APP/0]      OUT 2016-05-03 10:14:56.915 ERROR 14 --- [pool-1-thread-1] o.c.autosleep.worker.ApplicationStopper  : unsuspected error
2016-05-03T10:14:56.91+0000 [APP/0]      OUT java.lang.IllegalStateException: Subscriber timed out
2016-05-03T10:14:56.91+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.remote.CloudFoundryApi.getApplicationActivity(CloudFoundryApi.java:182)
2016-05-03T10:14:56.91+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.handleApplicationEnrolled(ApplicationStopper.java:89)
2016-05-03T10:14:56.91+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.lambda$run$0(ApplicationStopper.java:131)
2016-05-03T10:14:56.91+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.util.ApplicationLocker.executeThreadSafe(ApplicationLocker.java:28)
2016-05-03T10:14:56.91+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.run(ApplicationStopper.java:125)
2016-05-03T10:14:56.91+0000 [APP/0]      OUT    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2016-05-03T10:14:56.91+0000 [APP/0]      OUT    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2016-05-03T10:14:56.91+0000 [APP/0]      OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
2016-05-03T10:14:56.91+0000 [APP/0]      OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
2016-05-03T10:14:56.91+0000 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-05-03T10:14:56.91+0000 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-05-03T10:14:56.91+0000 [APP/0]      OUT    at java.lang.Thread.run(Thread.java:745)
2016-05-03T10:15:01.08+0000 [APP/0]      OUT 2016-05-03 10:15:01.087  INFO 14 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-05-03T10:15:01.16+0000 [APP/0]      OUT 2016-05-03 10:15:01.157  INFO 14 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2016-05-03T10:15:02.03+0000 [APP/0]      OUT 2016-05-03 10:15:02.036  INFO 14 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2016-05-03T10:15:02.06+0000 [APP/0]      OUT 2016-05-03 10:15:02.067  INFO 14 --- [           main] org.cloudfoundry.autosleep.Application   : Started Application in 89.953 seconds (JVM running for 92.625)
2016-05-03T10:15:02.20+0000 [CELL/0]     OUT Container became healthy
2016-05-03T10:16:58.88+0000 [APP/0]      OUT 2016-05-03 10:16:58.888 ERROR 14 --- [cloud-foundry-1] reactor.core.publisher.SchedulerGroup    : Unrouted exception
2016-05-03T10:16:58.88+0000 [APP/0]      OUT reactor.core.util.Exceptions$UpstreamException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.util.Exceptions.wrapUpstream(Exceptions.java:342)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.util.Exceptions.failUpstream(Exceptions.java:154)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.util.Exceptions.onErrorDropped(Exceptions.java:235)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.rx.StreamBlock$StreamBlockSubscriber.onError(StreamBlock.java:130)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.publisher.FluxPublishOn$PublishOnPipeline.onError(FluxPublishOn.java:142)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.subscriber.SignalEmitter.onNext(SignalEmitter.java:472)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at org.cloudfoundry.client.spring.util.AbstractSpringOperations$2$1.accept(AbstractSpringOperations.java:86)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at org.cloudfoundry.client.spring.util.AbstractSpringOperations$2$1.accept(AbstractSpringOperations.java:78)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.publisher.FluxYieldingEmitter$YieldingSignalEmitter.request(FluxYieldingEmitter.java:76)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.util.DeferredSubscription.set(DeferredSubscription.java:71)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.publisher.FluxPublishOn$PublishOnPipeline.onSubscribe(FluxPublishOn.java:131)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.subscriber.SignalEmitter.start(SignalEmitter.java:170)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.publisher.FluxYieldingEmitter.subscribe(FluxYieldingEmitter.java:43)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.rx.StreamSource.subscribe(StreamSource.java:71)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.util.ScalarSubscription.trySubscribeScalarMap(ScalarSubscription.java:93)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:93)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.rx.StreamSource.subscribe(StreamSource.java:71)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.publisher.FluxPublishOn$SourceSubscribeTask.run(FluxPublishOn.java:318)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1072)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1054)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.publisher.WorkQueueProcessor$QueueSubscriberLoop.run(WorkQueueProcessor.java:849)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at java.lang.Thread.run(Thread.java:745)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at java.util.ArrayList.get(ArrayList.java:429)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.remote.CloudFoundryApi$2.onNext(CloudFoundryApi.java:152)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.remote.CloudFoundryApi$2.onNext(CloudFoundryApi.java:148)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:85)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.rx.StreamBlock$StreamBlockSubscriber.onNext(StreamBlock.java:124)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.publisher.FluxPublishOn$PublishOnPipeline.onNext(FluxPublishOn.java:136)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.subscriber.SignalEmitter.emit(SignalEmitter.java:198)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    at reactor.core.subscriber.SignalEmitter.onNext(SignalEmitter.java:444)
2016-05-03T10:16:58.88+0000 [APP/0]      OUT    ... 18 common frames omitted
2016-05-03T10:17:06.52+0000 [APP/0]      OUT 2016-05-03 10:17:06.522 ERROR 14 --- [pool-1-thread-2] o.c.autosleep.worker.ApplicationStopper  : unsuspected error
2016-05-03T10:17:06.52+0000 [APP/0]      OUT java.lang.IllegalStateException: Subscriber timed out
2016-05-03T10:17:06.52+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.remote.CloudFoundryApi.getApplicationActivity(CloudFoundryApi.java:182)
2016-05-03T10:17:06.52+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.handleApplicationEnrolled(ApplicationStopper.java:89)
2016-05-03T10:17:06.52+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.lambda$run$0(ApplicationStopper.java:131)
2016-05-03T10:17:06.52+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.util.ApplicationLocker.executeThreadSafe(ApplicationLocker.java:28)
2016-05-03T10:17:06.52+0000 [APP/0]      OUT    at org.cloudfoundry.autosleep.worker.ApplicationStopper.run(ApplicationStopper.java:125)
2016-05-03T10:17:06.52+0000 [APP/0]      OUT    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2016-05-03T10:17:06.52+0000 [APP/0]      OUT    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2016-05-03T10:17:06.52+0000 [APP/0]      OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
2016-05-03T10:17:06.52+0000 [APP/0]      OUT    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
2016-05-03T10:17:06.52+0000 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-05-03T10:17:06.52+0000 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-05-03T10:17:06.52+0000 [APP/0]      OUT    at java.lang.Thread.run(Thread.java:745)

**Comment by gberche-orange** [comment]
thanks @paltanmoy for reporting this issue. Suspecting this is caused by a slow CC API response. 

Can you please detail whether once the exception was thrown, the autosleep stopped putting application to sleep, or were you merely observing this stack trace once ?

Briefly scanning through the code at https://github.com/Orange-OpenSource/autosleep/blob/0f8592bf96f683d62d1beae2a0f2b5903fb60700/src/main/java/org/cloudfoundry/autosleep/worker/ApplicationStopper.java#L129-L134 this exception is caught, and next checks are still supposed to be scheduled.

It would be great if you still have related traces so that we can better understand whether the CC API was consistenty slow in your environment (i.e. exceeding the [8s timeout](https://github.com/Orange-OpenSource/autosleep/blob/v0.2.0/src/main/java/org/cloudfoundry/autosleep/config/Config.java#L12) ) , and can indicate which version of the autosleep you were reproducing the issue on.

**Comment by gberche-orange** [comment]
@paltanmoy ping

**Comment by paltanmoy** [comment]
@gberche-orange : I got this few times intermittently. Now I am not seeing this issue for quite some time. So closing this issue. Will re-open with concrete reproducible steps if it reappears.
