### ISSUE TITLE
Autosleep App will not start with Pivotal Cloud Foundry 1.11 

### ISSUE THREAD

**Issue by filidav** [Orange-OpenSource/autosleep#283]
This was working with 1.10

Any ideas about this error?

17-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:85)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.subscriber.SignalEmitter.onNext(SignalEmitter.java:444)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.UnicastProcessor.onNext(UnicastProcessor.java:213)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.subscriber.SignalEmitter.emit(SignalEmitter.java:198)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$null$1(AbstractSpringOperations.java:68)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxYieldingEmitter$YieldingSignalEmitter.request(FluxYieldingEmitter.java:72)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxPublishOn$PublishOnPipeline.onSubscribe(FluxPublishOn.java:126)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxYieldingEmitter.subscribe(FluxYieldingEmitter.java:43)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxPublishOn$SourceSubscribeTask.run(FluxPublishOn.java:308)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:169)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1081)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1063)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] ... 25 common frames omitted
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.UnicastProcessor.drain(UnicastProcessor.java:131)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:121)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxPublishOn$PublishOnPipeline.onNext(FluxPublishOn.java:131)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.util.DeferredSubscription.set(DeferredSubscription.java:71)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.subscriber.SignalEmitter.start(SignalEmitter.java:170)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:152)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at reactor.core.publisher.WorkQueueProcessor$QueueSubscriberLoop.run(WorkQueueProcessor.java:842)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2017-10-20T17:14:26.977-04:00 [APP/PROC/WEB/0] [OUT] ... 1 common frames omitted
2017-10-20T17:14:26.980-04:00 [APP/PROC/WEB/0] [ERR] Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
2017-10-20T17:14:26.980-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
2017-10-20T17:14:26.981-04:00 [APP/PROC/WEB/0] [ERR] at java.lang.Thread.run(Thread.java:748)
2017-10-20T17:14:26.981-04:00 [APP/PROC/WEB/0] [ERR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2017-10-20T17:14:26.981-04:00 [APP/PROC/WEB/0] [ERR] Caused by: java.lang.reflect.InvocationTargetException
2017-10-20T17:14:26.981-04:00 [APP/PROC/WEB/0] [ERR] at java.lang.reflect.Method.invoke(Method.java:498)
2017-10-20T17:14:26.981-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
2017-10-20T17:14:26.981-04:00 [APP/PROC/WEB/0] [ERR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2017-10-20T17:14:26.981-04:00 [APP/PROC/WEB/0] [ERR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2017-10-20T17:14:26.982-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
2017-10-20T17:14:26.982-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
2017-10-20T17:14:26.982-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
2017-10-20T17:14:26.982-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
2017-10-20T17:14:26.982-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
2017-10-20T17:14:26.982-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
2017-10-20T17:14:26.982-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
2017-10-20T17:14:26.982-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
2017-10-20T17:14:26.982-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
2017-10-20T17:14:26.982-04:00 [APP/PROC/WEB/0] [ERR] ... 1 more
2017-10-20T17:14:26.982-04:00 [APP/PROC/WEB/0] [ERR] Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getClient' defined in org.cloudfoundry.autosleep.access.cloudfoundry.config.CloudfoundryClientBuilder: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.cloudfoundry.client.CloudFoundryClient]: Factory method 'getClient' threw exception; nested exception is org.springframework.context.ApplicationContextException: Failed to build client; nested exception is java.lang.NullPointerException: The mapper returned a null value.
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.cloudfoundry.client.CloudFoundryClient]: Factory method 'getClient' threw exception; nested exception is org.springframework.context.ApplicationContextException: Failed to build client; nested exception is java.lang.NullPointerException: The mapper returned a null value.
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.cloudfoundry.autosleep.access.cloudfoundry.config.CloudfoundryClientBuilder.buildIfNeeded(CloudfoundryClientBuilder.java:97)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.cloudfoundry.autosleep.access.cloudfoundry.config.CloudfoundryClientBuilder$$EnhancerBySpringCGLIB$$a39858c7.CGLIB$getClient$0(<generated>)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.cloudfoundry.autosleep.access.cloudfoundry.config.CloudfoundryClientBuilder$$EnhancerBySpringCGLIB$$a39858c7$$FastClassBySpringCGLIB$$a623752b.invoke(<generated>)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.cloudfoundry.autosleep.WakeUpApplication.main(WakeUpApplication.java:42)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] ... 6 more
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.builder.SpringApplicationBuilder.configureAsChildIfNecessary(SpringApplicationBuilder.java:147)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:130)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] ... 24 more
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] Caused by: org.springframework.context.ApplicationContextException: Failed to build client; nested exception is java.lang.NullPointerException: The mapper returned a null value.
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.cloudfoundry.autosleep.access.cloudfoundry.config.CloudfoundryClientBuilder.getClient(CloudfoundryClientBuilder.java:110)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.cloudfoundry.autosleep.access.cloudfoundry.config.CloudfoundryClientBuilder$$EnhancerBySpringCGLIB$$a39858c7.getClient(<generated>)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at java.lang.reflect.Method.invoke(Method.java:498)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
2017-10-20T17:14:26.987-04:00 [APP/PROC/WEB/0] [ERR] at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
2017-10-20T17:14:26.988-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:121)
2017-10-20T17:14:26.988-04:00 [APP/PROC/WEB/0] [ERR] Caused by: java.lang.NullPointerException: The mapper returned a null value.
2017-10-20T17:14:26.988-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.publisher.FluxPublishOn$PublishOnPipeline.onNext(FluxPublishOn.java:131)
2017-10-20T17:14:26.988-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:85)
2017-10-20T17:14:26.988-04:00 [APP/PROC/WEB/0] [ERR] ... 25 more
2017-10-20T17:14:26.988-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.publisher.UnicastProcessor.drain(UnicastProcessor.java:131)
2017-10-20T17:14:26.988-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.publisher.UnicastProcessor.onNext(UnicastProcessor.java:213)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.subscriber.SignalEmitter.onNext(SignalEmitter.java:444)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.publisher.FluxYieldingEmitter$YieldingSignalEmitter.request(FluxYieldingEmitter.java:72)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:152)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.util.DeferredSubscription.set(DeferredSubscription.java:71)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.publisher.FluxPublishOn$SourceSubscribeTask.run(FluxPublishOn.java:308)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.publisher.WorkQueueProcessor$QueueSubscriberLoop.run(WorkQueueProcessor.java:842)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.subscriber.SignalEmitter.emit(SignalEmitter.java:198)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$null$1(AbstractSpringOperations.java:68)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.subscriber.SignalEmitter.start(SignalEmitter.java:170)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.publisher.FluxPublishOn$PublishOnPipeline.onSubscribe(FluxPublishOn.java:126)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.publisher.FluxYieldingEmitter.subscribe(FluxYieldingEmitter.java:43)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:169)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1081)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1063)
2017-10-20T17:14:26.989-04:00 [APP/PROC/WEB/0] [ERR] ... 1 more

**Comment by gberche-orange** [comment]
thanks @filidav for reporting this issue. I would suggest you to post additional traces of the cf-java-client interactions by enabling verbose wire traces 

You might want to try with

-Dlogging.level.cloudfoundry-client.request=DEBUG -Dlogging.level.cloudfoundry-client.response=DEBUG -Dlogging.level.stream=INFO -Dlogging.level.reactor.ipc.netty=INFO

**Comment by marcus-sds** [comment]
I have same issue.
It's cf-deployment. There is no error message with uaa and only log-api shows 

-------log-api error
2017/10/25 10:51:07 Connecting to 1 dopplers
2017/10/25 10:51:39 error receiving from doppler via gRPC context canceled
2017/10/25 10:51:39 Error while reading from stream (10.0.16.7:8082): rpc error: code = Canceled desc = context canceled
2017/10/25 10:51:39 Disconnecting from stream (10.0.16.7:8082) (doppler.disconnect=false) (ctx.disconnect=1)

-------push log
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT ERROR - main - o.c.a.a.c.c.CloudfoundryClientBuilder(96) - CloudFoundryApi - failure while login
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT java.lang.NullPointerException: The mapper returned a null value.
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:121)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:85)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at reactor.core.publisher.UnicastProcessor.drain(UnicastProcessor.java:131)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at reactor.core.publisher.UnicastProcessor.onNext(UnicastProcessor.java:213)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at reactor.core.publisher.FluxPublishOn$PublishOnPipeline.onNext(FluxPublishOn.java:131)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at reactor.core.subscriber.SignalEmitter.emit(SignalEmitter.java:198)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at reactor.core.subscriber.SignalEmitter.onNext(SignalEmitter.java:444)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at org.cloudfoundry.spring.util.AbstractSpringOperations.lambda$null$1(AbstractSpringOperations.java:68)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at reactor.core.publisher.FluxYieldingEmitter$YieldingSignalEmitter.request(FluxYieldingEmitter.java:72)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at reactor.core.util.DeferredSubscription.request(DeferredSubscription.java:92)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at reactor.core.publisher.FluxPublishOn$PublishOnPipeline.run(FluxPublishOn.java:164)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1081)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1063)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at reactor.core.publisher.WorkQueueProcessor$QueueSubscriberLoop.run(WorkQueueProcessor.java:842)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT     at java.lang.Thread.run(Thread.java:748)
   2017-10-25T08:57:40.18+0000 [APP/PROC/WEB/0] OUT WARN  - main - o.s.c.a.AnnotationConfigApplicationContext(546) - Exception encountered during context initialization - 
cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getLogClient' 
defined in org.cloudfoundry.autosleep.access.cloudfoundry.config.CloudfoundryClientBuilder: Bean instantiation via factory method failed; 
nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.cloudfoundry.logging.LoggingClient]: 
Factory method 'getLogClient' threw exception; nested exception is org.springframework.context.ApplicationContextException: 
Failed to build client; nested exception is java.lang.NullPointerException: The mapper returned a null value.
   2017-10-25T08:57:40.19+0000 [APP/PROC/WEB/0] OUT ERROR - main - o.s.b.SpringApplication(827) - Application startup failed

**Comment by filidav** [comment]
I opened Issue 285 with debug logs as requested
