### ISSUE TITLE
Autosleep breaking when registering as broker with pcf java buildpack v4.19.1

### ISSUE THREAD

**Issue by mindprogenitor** [Orange-OpenSource/autosleep#297]
We've tried to upgrade autosleep to the latest java buildpack and ended up having a jackson error during the broker registration step. The error is a bit odd as we haven't changed any dependency versions, but it seems that in the new version it is getting the jackson dependencies from the apring auto reconfiguration file instead of the war:

   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT  java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonGenerator.writeStartObject(Ljava/lang/Object;)V
   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT 	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:515) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT 	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:30) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT 	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:416) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT 	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1425) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT 	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:951) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT 	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:269) ~[spring-web-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT 	at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:100) ~[spring-web-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:222) ~[spring-webmvc-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:183) ~[spring-webmvc-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT 	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:81) ~[spring-web-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:126) ~[spring-webmvc-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:832) ~[spring-webmvc-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:743) ~[spring-webmvc-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961) ~[spring-webmvc-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
   2019-06-19T07:37:22.27+0000 [APP/PROC/WEB/0] OUT 	... 27 common frames omitted

**Comment by gberche-orange** [comment]
@mindprogenitor thanks for raising the issue. 

Might be worth checking if indeed the auto config jar contains jackson classes and if so raise a bug on the associated github repo.
